/** Plain-language explanations for OFP labels, shown as hover / focus tips. */
export const G: Record<string, string> = {
  // Page 1 header
  RELEASE: "Time (UTC) and date the dispatcher released this flight plan",
  OFP: "Operational Flight Plan number — increments each time the plan is re-issued",
  "WX PROG": "Valid times of the forecast upper winds and temperatures used to plan the route (prognostic charts, 3-hourly steps around the flight), as DDHH UTC",
  OBS: "Base time of the forecast model run each WX PROG comes from (the observations it was computed from), as DDHH UTC. One per WX PROG; a later OBS means fresher forecast data",
  "ATC C/S": "ATC callsign filed in the ICAO flight plan (item 7)",
  "CRZ SYS": "Cruise speed schedule — the cost index the FMS will fly",
  CI: "Cost Index: ratio of time cost to fuel cost. 0 = max range / min fuel, higher = faster",
  "GND DIST": "Ground distance along the planned route, NM",
  "AIR DIST": "Air distance — ground distance corrected for wind; what the aircraft actually flies through the air mass, NM",
  "G/C DIST": "Great-circle distance: the shortest possible distance between departure and destination, NM",
  "AVG WIND": "Average wind direction/speed along the route (° true / kt)",
  "AVG W/C": "Average wind component. M = headwind (minus), P = tailwind (plus), kt",
  "AVG ISA": "Average temperature deviation from the International Standard Atmosphere, °C",
  "AVG FF": "Average fuel flow for the whole flight (both engines), per hour",
  "FUEL BIAS": "Performance factor applied to fuel burn to account for aircraft degradation, %",
  STA: "Scheduled Time of Arrival (UTC)",
  CTOT: "Calculated Take-Off Time slot issued by Network Manager (Eurocontrol) — blank if none",
  TOW: "Take-Off Weight",
  LAW: "Landing Weight (Landing Actual Weight)",
  ZFW: "Zero Fuel Weight: aircraft + payload, without usable fuel",
  MAXIMUM: "Structural / certified limits for this airframe",
  ESTIMATED: "Planned weights for this flight",
  ALTN: "Destination alternate airport",
  "TKOF ALTN": "Take-off alternate — required when weather at departure is below landing minima",
  "FL STEPS": "Planned cruise flight levels and the fixes where each step climb starts",
  "DISP RMKS": "Dispatcher remarks",
  // Fuel
  TRIP: "Fuel from take-off to landing at destination",
  "CONT 15 MIN": "Contingency fuel — covers unforeseen factors (here: 15 minutes holding)",
  CONT: "Contingency fuel — covers unforeseen factors",
  FINRES: "Final reserve: 30 min holding at 1500 ft above the alternate. Must never be used in normal ops",
  "MINIMUM T/OFF FUEL": "Minimum fuel required at take-off (trip + contingency + alternate + final reserve)",
  EXTRA: "Discretionary / company extra fuel above the minimum",
  "T/OFF FUEL": "Fuel on board at the start of the take-off roll",
  TAXI: "Fuel burnt from engine start to take-off",
  "BLOCK FUEL": "Total fuel on board at off-blocks (ramp fuel) — the figure to load",
  "PIC EXTRA": "Extra fuel added at the captain's discretion",
  "TOTAL FUEL": "Block fuel plus PIC extra",
  "FMC INFO": "Values to enter into the Flight Management Computer",
  "FINRES+ALTN": "Reserve entry for the FMS (final reserve + alternate fuel)",
  "TRIP+TAXI": "Fuel expected to be burnt on this sector including taxi",
  TANKERING: "Carrying extra fuel to avoid refuelling at destination; recommended only when price difference outweighs the extra burn",
  // Alternate / impacts
  TRK: "Track to the alternate, degrees",
  DST: "Distance to the alternate, NM",
  VIA: "Routing to the alternate",
  FL: "Flight level (hundreds of feet)",
  WC: "Wind component: M = headwind, P = tailwind (kt)",
  "MEL/CDL": "Minimum Equipment List / Configuration Deviation List items affecting this flight",
  "ROUTE ID": "Company route identifier",
  "OPERATIONAL IMPACTS": "How trip fuel and time change if weight, flight level or speed differ from plan",
  // Times & weights
  OUT: "Off-blocks: the aircraft leaves the gate",
  OFF: "Wheels off the runway (take-off)",
  ON: "Wheels on the runway (landing)",
  IN: "On-blocks: the aircraft arrives at the gate",
  "BLOCK TIME": "OUT to IN — gate-to-gate time",
  PAX: "Passengers on board",
  "BAG/CARGO": "Baggage and cargo mass (tonnes)",
  PAYLOAD: "Passengers + baggage + cargo (tonnes)",
  FUEL: "Fuel on board (tonnes)",
  "STAB TRIM": "Take-off stabiliser (THS) trim setting from the load sheet",
  "POSS EXTRA": "Additional fuel that could be loaded before hitting a weight limit (tonnes)",
  ATIS: "Automatic Terminal Information Service — copy the broadcast here",
  RVSM: "Reduced Vertical Separation Minimum check: compare left, standby and right altimeters before entering RVSM airspace",
  "DD CHECK": "Driftdown terrain check — engine failure en-route with terrain clearance",
  "DP CHECK": "Depressurisation terrain check — emergency descent with terrain clearance",
  // Flight log
  AWY: "Airway or procedure used to reach this point",
  POSITION: "Waypoint / navaid name",
  IDENT: "Waypoint identifier as entered in the FMS",
  FREQ: "Navaid frequency",
  LAT: "Latitude (degrees, decimal minutes)",
  LONG: "Longitude (degrees, decimal minutes)",
  EET: "Estimated Elapsed Time for this leg (HHMM)",
  TTLT: "Total elapsed time from take-off (HHMM)",
  ETO: "Estimated Time Over — fill in en-route",
  ATO: "Actual Time Over — fill in en-route",
  MORA: "Minimum Off-Route Altitude, hundreds of feet — clears terrain by 1000 ft (2000 ft in mountains) within 10 NM",
  DIS: "Leg distance, NM",
  RDIS: "Remaining distance to destination, NM",
  IMT: "Initial Magnetic Track of the leg, degrees",
  ITT: "Initial True Track of the leg, degrees",
  MN: "Mach number",
  TAS: "True airspeed, kt",
  GS: "Ground speed, kt",
  WIND: "Forecast wind at this point: direction ° true / speed kt",
  COMP: "Wind component: M = headwind, P = tailwind (kt)",
  SHR: "Wind shear value (turbulence indicator)",
  OAT: "Outside Air Temperature, °C (M = minus)",
  TDV: "Temperature deviation from ISA, °C",
  TRP: "Tropopause height (flight level)",
  EFOB: "Estimated Fuel On Board at this point (tonnes)",
  AFOB: "Actual Fuel On Board — fill in en-route",
  RETO: "Revised Estimated Time Over: the Actual OFF from Times & weights plus TTLT",
  TFOB: "Total fuel on board with PIC extra: EFOB plus the extra loaded, less the extra fuel burnt carrying it (from the OFP's weight-change impact)",
  PBRN: "Planned fuel burnt since take-off (tonnes)",
  ABRN: "Actual fuel burnt — fill in en-route",
  TOC: "Top of Climb",
  TOD: "Top of Descent",
  "MOST CRITICAL MORA": "Highest minimum off-route altitude on the route, and the point with the strongest wind shear",
  // FPL
  PBN: "Performance-Based Navigation capabilities",
  DOF: "Date of flight (YYMMDD)",
  REG: "Aircraft registration",
  "EET/": "Estimated elapsed time to each FIR boundary",
  OPR: "Aircraft operator (ICAO designator)",
  PER: "Aircraft performance category (approach speed band)",
  RMK: "Other remarks",
  // TLR
  APT: "Airport",
  PRWY: "Planned runway",
  POAT: "Planned outside air temperature, °C",
  PWIND: "Planned wind: direction, M = magnetic, speed (kt)",
  PQNH: "Planned QNH, hPa",
  PMRTW: "Planned maximum runway take-off weight (×10 kg)",
  PMRLW: "Planned maximum runway landing weight (×10 kg)",
  FLP: "Flap configuration",
  MT: "Assumed / FLEX temperature for reduced-thrust take-off, °C",
  V1: "Decision speed: last point to reject take-off, kt",
  VR: "Rotation speed, kt",
  V2: "Take-off safety speed (engine-out climb), kt",
  PTOW: "Planned take-off weight (×10 kg)",
  MFPTW: "Maximum flex take-off weight for the planned conditions (×10 kg)",
  LIMIT: "The limiting factor: AFM = certified maximum, FLD = field length, OBS = obstacles, CLB = climb, TIRE, BRKE…",
  PLDW: "Planned landing weight (×10 kg)",
  MTOW: "Maximum take-off weight for this runway (×10 kg)",
  VREF: "Reference landing speed, kt",
  LDW: "Landing weight (×10 kg)",
  CONFIG: "Thrust mode and configuration: FLEX = derated take-off at assumed temperature, TOGA = full thrust",
  PMTOW: "Planned maximum take-off weight for the runway (×10 kg)",
  LENGTH: "Runway length available, ft",
  FACTORED: "Required distance including regulatory safety factors (1.67 dry, +15% wet)",
  ACTUAL: "Unfactored demonstrated landing distance",
};

export const tip = (k: string | null | undefined) => (k ? G[k] ?? G[k.toUpperCase()] ?? null : null);

/** ICAO FPL item 10a equipment letters */
export const EQUIP: Record<string, string> = {
  S: "Standard: VHF RTF, VOR and ILS",
  N: "No COM/NAV equipment carried",
  A: "GBAS landing system",
  B: "LPV (APV with SBAS)",
  C: "LORAN C",
  D: "DME",
  E1: "FMC WPR ACARS",
  E2: "D-FIS ACARS",
  E3: "PDC ACARS",
  F: "ADF",
  G: "GNSS",
  H: "HF RTF",
  I: "Inertial navigation",
  J1: "CPDLC ATN VDL Mode 2",
  K: "MLS",
  L: "ILS",
  M1: "ATC SATVOICE (INMARSAT)",
  O: "VOR",
  R: "PBN approved",
  T: "TACAN",
  U: "UHF RTF",
  V: "VHF RTF",
  W: "RVSM approved",
  X: "MNPS approved",
  Y: "VHF with 8.33 kHz spacing",
  Z: "Other equipment (see item 18)",
};

/** ICAO FPL item 10b surveillance codes */
export const SURV: Record<string, string> = {
  L: "Transponder Mode S with ADS-B and enhanced surveillance",
  S: "Transponder Mode S with pressure altitude and aircraft ID",
  E: "Transponder Mode S with ADS-B extended squitter",
  H: "Transponder Mode S with enhanced surveillance",
  B1: "ADS-B out on 1090 MHz",
  B2: "ADS-B out and in on 1090 MHz",
  D1: "ADS-C with FANS 1/A",
  G1: "ADS-C with ATN",
};

export const PBN: Record<string, string> = {
  A1: "RNAV 10 (RNP 10)",
  B1: "RNAV 5 — all permitted sensors",
  B2: "RNAV 5 GNSS",
  C1: "RNAV 2 — all permitted sensors",
  D1: "RNAV 1 — all permitted sensors",
  L1: "RNP 4",
  O1: "Basic RNP 1 — all permitted sensors",
  S1: "RNP APCH",
  S2: "RNP APCH with BARO-VNAV",
  T1: "RNP AR APCH with RF",
  T2: "RNP AR APCH without RF",
};

export const FLIGHT_RULES: Record<string, string> = { I: "IFR", V: "VFR", Y: "IFR then VFR", Z: "VFR then IFR" };
export const FLIGHT_TYPE: Record<string, string> = { S: "Scheduled air service", N: "Non-scheduled", G: "General aviation", M: "Military", X: "Other" };
export const WAKE: Record<string, string> = { L: "Light", M: "Medium", H: "Heavy", J: "Super" };

/** Splits "SDE2E3FGHIRWXY" into ICAO equipment codes. */
export function splitEquip(s: string): string[] {
  const out: string[] = [];
  for (let i = 0; i < s.length; i++) {
    const two = s.slice(i, i + 2);
    if (/^[A-Z]\d$/.test(two)) {
      out.push(two);
      i++;
    } else out.push(s[i]);
  }
  return out;
}

export const NOTAM_PREFIX: Record<string, string> = {
  CLSD: "closed",
  "U/S": "unserviceable",
  AVBL: "available",
  "NOT AVBL": "not available",
  WIP: "work in progress",
  OBST: "obstacle",
  TWY: "taxiway",
  RWY: "runway",
  APCH: "approach",
  ACFT: "aircraft",
  LTD: "limited",
  PSN: "position",
  HGT: "height",
  ELEV: "elevation",
  LGT: "lighting",
  ARP: "aerodrome reference point",
  RDL: "radial",
  SUP: "supplement",
  AD: "aerodrome",
};
